server:
  port: 8884
  address: 0.0.0.0
  servlet:
    context-path: /


spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        #url: jdbc:mysql://localhost:3306/soul-open?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&failOverReadOnly=false&autoReconnect=true
        url: jdbc:mysql://localhost:3306/tcc_order?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        #password: dev-mysql-R3ND7N4zvjYt0Wvw
        password: andy123L
    application:
      name: order-service
    redis:
      host: localhost
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数(使用负值表示没有限制) 默认为8
          max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
          max-idle: 8 # 连接池中的最大空闲连接 默认为8
          min-idle: 0 # 连接池中的最小空闲连接 默认为 0


mybatis:
  type-aliases-package: com.mepeng.cn.SevenPen.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
 instance:
   prefer-ip-address: true

#Ribbon的负载均衡策略
hmilyOrder :
     ribbon:
        NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
        MaxAutoRetriesNextServer : 0
feign:
  hystrix:
     enabled : true
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        org.dromara.hmily.bonuspoint: debug
        org.dromara.hmily.lottery: debug
        org.dromara.hmily: debug
        io.netty: info
        com.mepeng.cn.SevenPen: debug
    path: "./logs"


